apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
    managed-by: portainer-run
  annotations:
    portainer-run/git-target-id: e9f5e5f5-11f5-4110-a47d-d3ce7748e8fa
    portainer-run/git-branch: main
    portainer-run/git-path: default/my-app.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        managed-by: portainer-run
    spec:
      containers:
        - name: app
          image: nginx:alpine
          imagePullPolicy: Always
