apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
    managed-by: portainer-run
  annotations:
    portainer-run/git-target-id: 0daa0b9b-70fd-4de8-9c8f-7dc69ab79b1e
    portainer-run/git-branch: main
    portainer-run/git-path: default/my-app.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        managed-by: portainer-run
    spec:
      containers:
        - name: app
          image: nginx
          imagePullPolicy: Always
