apiVersion: v2
name: portainer-run
description: Helm chart used to deploy Portainer-Run on Kubernetes
home: https://www.portainer.io
icon: https://github.com/portainer/portainer/raw/develop/app/assets/ico/apple-touch-icon.png
type: application
version: 0.2.4
appVersion: "latest"
maintainers:
  - name: Portainer
    url: https://www.portainer.io
sources:
  - https://github.com/portainer/portainer-run
